services:
  sMysql:
    image: mysql:9.1
    container_name: cMysql
    environment:
      MYSQL_ROOT_PASSWORD: FjeClot2425@
      MYSQL_DATABASE: bdPj9f4a87apl2
      MYSQL_USER: asix2
      MYSQL_PASSWORD: FjeClot2425#
    ports:
      - "33306:3306"
    volumes:
      - ./sql:/sql
      - vDades:/var/lib/mysql
    networks:
      - xPj9f4a87apl2

  sWebApp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cWebApp
    image: iwebapp:1.0  # Aquí lo he cambiado a minúsculas
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - sMysql
    networks:
      - xPj9f4a87apl2

networks:
  xPj9f4a87apl2:
    driver: bridge

volumes:
  vDades:
    name: dades
