services:
  apache:
    image: httpd:latest
    container_name: apache-container
    volumes:
      - ./codi/starship-sorades-13k:/usr/local/apache2/htdocs
    expose:
      - 80

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
